### ISSUE TITLE
Seperate files for routes

### ISSUE THREAD

**Issue by Weredime** [Looky1173/Incubator#2]
For example, in /api/scratch-jams/[...jams].js we could split into many other files.

I'm working on an implementation

**Comment by Looky1173** [comment]
This would be very nice! You could extract the various components into the folder `src/components/Jam`, just like I've done for some components already:
![image](https://user-images.githubusercontent.com/60521810/177192843-e9d10115-ba87-4d34-8838-480023f6b6c8.png)

**Comment by Weredime** [comment]
Personally I don't think I can do this since I don't know **much** about Next.js and it's architecture.

**Comment by Looky1173** [comment]
Okay, no problem!

**Comment by Looky1173** [comment]
Done in 7c4135ec6518cdead904a98455d260c54df68464, closing.
